"""Single definition of every constant (Constitution 4.5). Mirrored in contracts/constants.json."""
GRAVITY_MS2 = 9.81
FUSION_RADIUS_M = 20
POI_INFLUENCE_RADIUS_M = 300
SCHOOL_ZONE_RADIUS_M = 100
SEVERITY_BUCKETS = {"low": "< 0.35", "medium": "0.35 to < 0.60", "high": "0.60 to < 0.80", "critical": ">= 0.80"}
BUCKET_LOWER = {"medium": 0.35, "high": 0.60, "critical": 0.80}
HIGH_SEVERITY_THRESHOLD = 0.60
REPAIR_MINUTES = {"low": 15, "medium": 25, "high": 35, "critical": 40}
TRAVEL_SPEED_KMH = 20
DETOUR_FACTOR = 1.3
PROXIMITY_HORIZON_MIN = 30
FACTOR_FLOOR = 0.1
AGING_BONUS_PER_DAY = 0.02
AGING_BONUS_CAP = 0.20
SHIFT_MINUTES_DEFAULT = 480
MAX_CREWS = 3
MIN_PEAK_Z_DEVIATION = 3.0
DEVICE_DEDUP_WINDOW_MIN = 10
MAX_PHOTO_MB = 5
MAX_PHOTOS_PER_POTHOLE_RETURNED = 5
BATCH_MAX_EVENTS = 200
PHOTO_VERIFY_MAX_DISTANCE_M = 100
PHOTO_MISMATCH_DISTANCE_M = 300
PHOTO_MAX_AGE_HOURS = 24
PHOTO_STALE_DAYS = 7
UNVERIFIED_PHOTO_WEIGHT_FACTOR = 0.5
PHOTO_DUPLICATE_HAMMING_MAX = 6
PHOTO_HASH_LOOKBACK_DAYS = 30
GPS_ACCURACY_CAP_M = 300
MAX_IMAGE_PIXELS = 25000000

CONSTANTS = {
    "GRAVITY_MS2": GRAVITY_MS2, "FUSION_RADIUS_M": FUSION_RADIUS_M,
    "POI_INFLUENCE_RADIUS_M": POI_INFLUENCE_RADIUS_M, "SCHOOL_ZONE_RADIUS_M": SCHOOL_ZONE_RADIUS_M,
    "SEVERITY_BUCKETS": SEVERITY_BUCKETS, "HIGH_SEVERITY_THRESHOLD": HIGH_SEVERITY_THRESHOLD,
    "REPAIR_MINUTES": REPAIR_MINUTES, "TRAVEL_SPEED_KMH": TRAVEL_SPEED_KMH,
    "DETOUR_FACTOR": DETOUR_FACTOR, "PROXIMITY_HORIZON_MIN": PROXIMITY_HORIZON_MIN,
    "FACTOR_FLOOR": FACTOR_FLOOR, "AGING_BONUS_PER_DAY": AGING_BONUS_PER_DAY,
    "AGING_BONUS_CAP": AGING_BONUS_CAP, "SHIFT_MINUTES_DEFAULT": SHIFT_MINUTES_DEFAULT,
    "MAX_CREWS": MAX_CREWS, "MIN_PEAK_Z_DEVIATION": MIN_PEAK_Z_DEVIATION,
    "DEVICE_DEDUP_WINDOW_MIN": DEVICE_DEDUP_WINDOW_MIN, "MAX_PHOTO_MB": MAX_PHOTO_MB,
    "MAX_PHOTOS_PER_POTHOLE_RETURNED": MAX_PHOTOS_PER_POTHOLE_RETURNED,
    "BATCH_MAX_EVENTS": BATCH_MAX_EVENTS, "PHOTO_VERIFY_MAX_DISTANCE_M": PHOTO_VERIFY_MAX_DISTANCE_M,
    "PHOTO_MISMATCH_DISTANCE_M": PHOTO_MISMATCH_DISTANCE_M, "PHOTO_MAX_AGE_HOURS": PHOTO_MAX_AGE_HOURS,
    "PHOTO_STALE_DAYS": PHOTO_STALE_DAYS, "UNVERIFIED_PHOTO_WEIGHT_FACTOR": UNVERIFIED_PHOTO_WEIGHT_FACTOR,
    "PHOTO_DUPLICATE_HAMMING_MAX": PHOTO_DUPLICATE_HAMMING_MAX,
    "PHOTO_HASH_LOOKBACK_DAYS": PHOTO_HASH_LOOKBACK_DAYS, "GPS_ACCURACY_CAP_M": GPS_ACCURACY_CAP_M,
    "MAX_IMAGE_PIXELS": MAX_IMAGE_PIXELS,
}
